// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: homes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createHome = `-- name: CreateHome :one
INSERT INTO homes (user_id, name, lat, lon)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, lat, lon, created_at
`

type CreateHomeParams struct {
	UserID uuid.UUID
	Name   string
	Lat    float64
	Lon    float64
}

func (q *Queries) CreateHome(ctx context.Context, arg CreateHomeParams) (Home, error) {
	row := q.db.QueryRow(ctx, createHome,
		arg.UserID,
		arg.Name,
		arg.Lat,
		arg.Lon,
	)
	var i Home
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHome = `-- name: DeleteHome :execrows
DELETE FROM homes WHERE id = $2 AND user_id = $1
`

type DeleteHomeParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteHome(ctx context.Context, arg DeleteHomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHome, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const homeByID = `-- name: HomeByID :one
SELECT id, user_id, name, lat, lon, created_at FROM homes WHERE id = $2 AND user_id = $1
`

type HomeByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) HomeByID(ctx context.Context, arg HomeByIDParams) (Home, error) {
	row := q.db.QueryRow(ctx, homeByID, arg.UserID, arg.ID)
	var i Home
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
	)
	return i, err
}

const listHomes = `-- name: ListHomes :many
SELECT id, user_id, name, lat, lon, created_at FROM homes WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListHomes(ctx context.Context, userID uuid.UUID) ([]Home, error) {
	rows, err := q.db.Query(ctx, listHomes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Home
	for rows.Next() {
		var i Home
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripHomes = `-- name: ListTripHomes :many
SELECT DISTINCT h.id, h.name
FROM homes h
JOIN itinerary_items i ON h.id IN (i.origin_home_id, i.destination_home_id)
WHERE i.trip_id = $1
`

type ListTripHomesRow struct {
	ID   uuid.UUID
	Name string
}

// Homes referenced by a trip's itinerary legs (possibly other members'),
// for labeling "(home) Name" in the UI.
func (q *Queries) ListTripHomes(ctx context.Context, tripID uuid.UUID) ([]ListTripHomesRow, error) {
	rows, err := q.db.Query(ctx, listTripHomes, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripHomesRow
	for rows.Next() {
		var i ListTripHomesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
