// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countItemsForDay = `-- name: CountItemsForDay :one

SELECT count(*) FROM itinerary_items WHERE trip_id = $1 AND day = $2 AND layer_id = $3
`

type CountItemsForDayParams struct {
	TripID  uuid.UUID
	Day     time.Time
	LayerID uuid.UUID
}

// Reordering is scoped to one layer (#73 slice 2): each layer's board
// orders its own items, so positions may repeat across layers on a day.
func (q *Queries) CountItemsForDay(ctx context.Context, arg CountItemsForDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsForDay, arg.TripID, arg.Day, arg.LayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one

INSERT INTO itinerary_items (trip_id, stop_id, destination_stop_id, origin_home_id, destination_home_id, day, start_time, end_time, title, category, notes, cost_cents, currency, address, lat, lon, layer_id, destination_address, destination_lat, destination_lon, timezone, position)
VALUES ($1, $2, $3, $4, $5, $6,
        NULLIF($7::text, '')::time, NULLIF($8::text, '')::time,
        $9, $10, $11, $12, $13,
        $14, $15, $16, $17,
        $18, $19, $20,
        $21,
        (SELECT COALESCE(MAX(position) + 1, 0) FROM itinerary_items i WHERE i.trip_id = $1 AND i.day = $6))
RETURNING id, trip_id, stop_id, day,
          CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time,
          title, category, notes, cost_cents, currency, position,
          CAST(COALESCE(to_char(end_time, 'HH24:MI'), '') AS text) AS end_time,
          destination_stop_id, origin_home_id, destination_home_id, address, lat, lon, layer_id,
          destination_address, destination_lat, destination_lon, timezone
`

type CreateItemParams struct {
	TripID             uuid.UUID
	StopID             *uuid.UUID
	DestinationStopID  *uuid.UUID
	OriginHomeID       *uuid.UUID
	DestinationHomeID  *uuid.UUID
	Day                time.Time
	StartTime          string
	EndTime            string
	Title              string
	Category           ItineraryCategory
	Notes              string
	CostCents          *int64
	Currency           *string
	Address            string
	Lat                *float64
	Lon                *float64
	LayerID            uuid.UUID
	DestinationAddress string
	DestinationLat     *float64
	DestinationLon     *float64
	Timezone           *string
}

type CreateItemRow struct {
	ID                 uuid.UUID
	TripID             uuid.UUID
	StopID             *uuid.UUID
	Day                time.Time
	StartTime          string
	Title              string
	Category           ItineraryCategory
	Notes              string
	CostCents          *int64
	Currency           *string
	Position           int32
	EndTime            string
	DestinationStopID  *uuid.UUID
	OriginHomeID       *uuid.UUID
	DestinationHomeID  *uuid.UUID
	Address            string
	Lat                *float64
	Lon                *float64
	LayerID            uuid.UUID
	DestinationAddress string
	DestinationLat     *float64
	DestinationLon     *float64
	Timezone           *string
}

// start_time/end_time are `time` columns exposed as "HH:MM" strings; ”
// means unset. NULLIF on the way in and COALESCE(to_char(...)) on the way
// out keep sqlc's generated types plain strings.
// Appends the item at the end of its day's ordering.
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.TripID,
		arg.StopID,
		arg.DestinationStopID,
		arg.OriginHomeID,
		arg.DestinationHomeID,
		arg.Day,
		arg.StartTime,
		arg.EndTime,
		arg.Title,
		arg.Category,
		arg.Notes,
		arg.CostCents,
		arg.Currency,
		arg.Address,
		arg.Lat,
		arg.Lon,
		arg.LayerID,
		arg.DestinationAddress,
		arg.DestinationLat,
		arg.DestinationLon,
		arg.Timezone,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StopID,
		&i.Day,
		&i.StartTime,
		&i.Title,
		&i.Category,
		&i.Notes,
		&i.CostCents,
		&i.Currency,
		&i.Position,
		&i.EndTime,
		&i.DestinationStopID,
		&i.OriginHomeID,
		&i.DestinationHomeID,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.LayerID,
		&i.DestinationAddress,
		&i.DestinationLat,
		&i.DestinationLon,
		&i.Timezone,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM itinerary_items WHERE id = $2 AND trip_id = $1
`

type DeleteItemParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.TripID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const itemByID = `-- name: ItemByID :one
SELECT id, trip_id, stop_id, day,
       CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time,
       title, category, notes, cost_cents, currency, position,
       CAST(COALESCE(to_char(end_time, 'HH24:MI'), '') AS text) AS end_time,
       destination_stop_id, origin_home_id, destination_home_id, address, lat, lon, layer_id,
       destination_address, destination_lat, destination_lon, timezone
FROM itinerary_items WHERE id = $2 AND trip_id = $1
`

type ItemByIDParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

type ItemByIDRow struct {
	ID                 uuid.UUID
	TripID             uuid.UUID
	StopID             *uuid.UUID
	Day                time.Time
	StartTime          string
	Title              string
	Category           ItineraryCategory
	Notes              string
	CostCents          *int64
	Currency           *string
	Position           int32
	EndTime            string
	DestinationStopID  *uuid.UUID
	OriginHomeID       *uuid.UUID
	DestinationHomeID  *uuid.UUID
	Address            string
	Lat                *float64
	Lon                *float64
	LayerID            uuid.UUID
	DestinationAddress string
	DestinationLat     *float64
	DestinationLon     *float64
	Timezone           *string
}

func (q *Queries) ItemByID(ctx context.Context, arg ItemByIDParams) (ItemByIDRow, error) {
	row := q.db.QueryRow(ctx, itemByID, arg.TripID, arg.ID)
	var i ItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StopID,
		&i.Day,
		&i.StartTime,
		&i.Title,
		&i.Category,
		&i.Notes,
		&i.CostCents,
		&i.Currency,
		&i.Position,
		&i.EndTime,
		&i.DestinationStopID,
		&i.OriginHomeID,
		&i.DestinationHomeID,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.LayerID,
		&i.DestinationAddress,
		&i.DestinationLat,
		&i.DestinationLon,
		&i.Timezone,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, trip_id, stop_id, day,
       CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time,
       title, category, notes, cost_cents, currency, position,
       CAST(COALESCE(to_char(end_time, 'HH24:MI'), '') AS text) AS end_time,
       destination_stop_id, origin_home_id, destination_home_id, address, lat, lon, layer_id,
       destination_address, destination_lat, destination_lon, timezone
FROM itinerary_items WHERE trip_id = $1 ORDER BY day, position, id
`

type ListItemsRow struct {
	ID                 uuid.UUID
	TripID             uuid.UUID
	StopID             *uuid.UUID
	Day                time.Time
	StartTime          string
	Title              string
	Category           ItineraryCategory
	Notes              string
	CostCents          *int64
	Currency           *string
	Position           int32
	EndTime            string
	DestinationStopID  *uuid.UUID
	OriginHomeID       *uuid.UUID
	DestinationHomeID  *uuid.UUID
	Address            string
	Lat                *float64
	Lon                *float64
	LayerID            uuid.UUID
	DestinationAddress string
	DestinationLat     *float64
	DestinationLon     *float64
	Timezone           *string
}

func (q *Queries) ListItems(ctx context.Context, tripID uuid.UUID) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.StopID,
			&i.Day,
			&i.StartTime,
			&i.Title,
			&i.Category,
			&i.Notes,
			&i.CostCents,
			&i.Currency,
			&i.Position,
			&i.EndTime,
			&i.DestinationStopID,
			&i.OriginHomeID,
			&i.DestinationHomeID,
			&i.Address,
			&i.Lat,
			&i.Lon,
			&i.LayerID,
			&i.DestinationAddress,
			&i.DestinationLat,
			&i.DestinationLon,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleItems = `-- name: ListVisibleItems :many
SELECT i.id, i.trip_id, i.stop_id, i.day,
       CAST(COALESCE(to_char(i.start_time, 'HH24:MI'), '') AS text) AS start_time,
       i.title, i.category, i.notes, i.cost_cents, i.currency, i.position,
       CAST(COALESCE(to_char(i.end_time, 'HH24:MI'), '') AS text) AS end_time,
       i.destination_stop_id, i.origin_home_id, i.destination_home_id, i.address, i.lat, i.lon, i.layer_id,
       i.destination_address, i.destination_lat, i.destination_lon, i.timezone
FROM itinerary_items i
JOIN itinerary_layers l ON l.id = i.layer_id AND l.visible
WHERE i.trip_id = $1 ORDER BY i.day, i.position, i.id
`

type ListVisibleItemsRow struct {
	ID                 uuid.UUID
	TripID             uuid.UUID
	StopID             *uuid.UUID
	Day                time.Time
	StartTime          string
	Title              string
	Category           ItineraryCategory
	Notes              string
	CostCents          *int64
	Currency           *string
	Position           int32
	EndTime            string
	DestinationStopID  *uuid.UUID
	OriginHomeID       *uuid.UUID
	DestinationHomeID  *uuid.UUID
	Address            string
	Lat                *float64
	Lon                *float64
	LayerID            uuid.UUID
	DestinationAddress string
	DestinationLat     *float64
	DestinationLon     *float64
	Timezone           *string
}

// The itinerary is the merge of visible layers — what shares, exports,
// and read-only views see.
func (q *Queries) ListVisibleItems(ctx context.Context, tripID uuid.UUID) ([]ListVisibleItemsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleItems, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleItemsRow
	for rows.Next() {
		var i ListVisibleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.StopID,
			&i.Day,
			&i.StartTime,
			&i.Title,
			&i.Category,
			&i.Notes,
			&i.CostCents,
			&i.Currency,
			&i.Position,
			&i.EndTime,
			&i.DestinationStopID,
			&i.OriginHomeID,
			&i.DestinationHomeID,
			&i.Address,
			&i.Lat,
			&i.Lon,
			&i.LayerID,
			&i.DestinationAddress,
			&i.DestinationLat,
			&i.DestinationLon,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offsetItemPositions = `-- name: OffsetItemPositions :exec
UPDATE itinerary_items SET position = position + $4 WHERE trip_id = $1 AND day = $2 AND layer_id = $3
`

type OffsetItemPositionsParams struct {
	TripID   uuid.UUID
	Day      time.Time
	LayerID  uuid.UUID
	Position int32
}

func (q *Queries) OffsetItemPositions(ctx context.Context, arg OffsetItemPositionsParams) error {
	_, err := q.db.Exec(ctx, offsetItemPositions,
		arg.TripID,
		arg.Day,
		arg.LayerID,
		arg.Position,
	)
	return err
}

const setItemPosition = `-- name: SetItemPosition :execrows
UPDATE itinerary_items SET position = $5 WHERE id = $4 AND trip_id = $1 AND day = $2 AND layer_id = $3
`

type SetItemPositionParams struct {
	TripID   uuid.UUID
	Day      time.Time
	LayerID  uuid.UUID
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetItemPosition(ctx context.Context, arg SetItemPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemPosition,
		arg.TripID,
		arg.Day,
		arg.LayerID,
		arg.ID,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE itinerary_items
SET stop_id = $1, destination_stop_id = $2,
    origin_home_id = $3, destination_home_id = $4, day = $5,
    start_time = NULLIF($6::text, '')::time,
    end_time = NULLIF($7::text, '')::time,
    title = $8, category = $9, notes = $10,
    cost_cents = $11, currency = $12,
    address = $13, lat = $14, lon = $15,
    layer_id = $16,
    destination_address = $17, destination_lat = $18, destination_lon = $19,
    timezone = $20
WHERE id = $21 AND trip_id = $22
RETURNING id, trip_id, stop_id, day,
          CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time,
          title, category, notes, cost_cents, currency, position,
          CAST(COALESCE(to_char(end_time, 'HH24:MI'), '') AS text) AS end_time,
          destination_stop_id, origin_home_id, destination_home_id, address, lat, lon, layer_id,
          destination_address, destination_lat, destination_lon, timezone
`

type UpdateItemParams struct {
	StopID             *uuid.UUID
	DestinationStopID  *uuid.UUID
	OriginHomeID       *uuid.UUID
	DestinationHomeID  *uuid.UUID
	Day                time.Time
	StartTime          string
	EndTime            string
	Title              string
	Category           ItineraryCategory
	Notes              string
	CostCents          *int64
	Currency           *string
	Address            string
	Lat                *float64
	Lon                *float64
	LayerID            uuid.UUID
	DestinationAddress string
	DestinationLat     *float64
	DestinationLon     *float64
	Timezone           *string
	ID                 uuid.UUID
	TripID             uuid.UUID
}

type UpdateItemRow struct {
	ID                 uuid.UUID
	TripID             uuid.UUID
	StopID             *uuid.UUID
	Day                time.Time
	StartTime          string
	Title              string
	Category           ItineraryCategory
	Notes              string
	CostCents          *int64
	Currency           *string
	Position           int32
	EndTime            string
	DestinationStopID  *uuid.UUID
	OriginHomeID       *uuid.UUID
	DestinationHomeID  *uuid.UUID
	Address            string
	Lat                *float64
	Lon                *float64
	LayerID            uuid.UUID
	DestinationAddress string
	DestinationLat     *float64
	DestinationLon     *float64
	Timezone           *string
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.StopID,
		arg.DestinationStopID,
		arg.OriginHomeID,
		arg.DestinationHomeID,
		arg.Day,
		arg.StartTime,
		arg.EndTime,
		arg.Title,
		arg.Category,
		arg.Notes,
		arg.CostCents,
		arg.Currency,
		arg.Address,
		arg.Lat,
		arg.Lon,
		arg.LayerID,
		arg.DestinationAddress,
		arg.DestinationLat,
		arg.DestinationLon,
		arg.Timezone,
		arg.ID,
		arg.TripID,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StopID,
		&i.Day,
		&i.StartTime,
		&i.Title,
		&i.Category,
		&i.Notes,
		&i.CostCents,
		&i.Currency,
		&i.Position,
		&i.EndTime,
		&i.DestinationStopID,
		&i.OriginHomeID,
		&i.DestinationHomeID,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.LayerID,
		&i.DestinationAddress,
		&i.DestinationLat,
		&i.DestinationLon,
		&i.Timezone,
	)
	return i, err
}
