// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countItemsForDay = `-- name: CountItemsForDay :one
SELECT count(*) FROM itinerary_items WHERE trip_id = $1 AND day = $2
`

type CountItemsForDayParams struct {
	TripID uuid.UUID
	Day    time.Time
}

func (q *Queries) CountItemsForDay(ctx context.Context, arg CountItemsForDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsForDay, arg.TripID, arg.Day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one

INSERT INTO itinerary_items (trip_id, stop_id, day, start_time, title, category, notes, cost_cents, currency, position)
VALUES ($1, $2, $3, NULLIF($4::text, '')::time,
        $5, $6, $7, $8, $9,
        (SELECT COALESCE(MAX(position) + 1, 0) FROM itinerary_items i WHERE i.trip_id = $1 AND i.day = $3))
RETURNING id, trip_id, stop_id, day, CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time, title, category, notes, cost_cents, currency, position
`

type CreateItemParams struct {
	TripID    uuid.UUID
	StopID    *uuid.UUID
	Day       time.Time
	StartTime string
	Title     string
	Category  ItineraryCategory
	Notes     string
	CostCents *int64
	Currency  *string
}

type CreateItemRow struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	StopID    *uuid.UUID
	Day       time.Time
	StartTime string
	Title     string
	Category  ItineraryCategory
	Notes     string
	CostCents *int64
	Currency  *string
	Position  int32
}

// start_time is a `time` column exposed as an "HH:MM" string; ” means
// unscheduled. NULLIF on the way in and COALESCE(to_char(...)) on the way
// out keep sqlc's generated types plain strings.
// Appends the item at the end of its day's ordering.
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.TripID,
		arg.StopID,
		arg.Day,
		arg.StartTime,
		arg.Title,
		arg.Category,
		arg.Notes,
		arg.CostCents,
		arg.Currency,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StopID,
		&i.Day,
		&i.StartTime,
		&i.Title,
		&i.Category,
		&i.Notes,
		&i.CostCents,
		&i.Currency,
		&i.Position,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM itinerary_items WHERE id = $2 AND trip_id = $1
`

type DeleteItemParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.TripID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const itemByID = `-- name: ItemByID :one
SELECT id, trip_id, stop_id, day, CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time, title, category, notes, cost_cents, currency, position
FROM itinerary_items WHERE id = $2 AND trip_id = $1
`

type ItemByIDParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

type ItemByIDRow struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	StopID    *uuid.UUID
	Day       time.Time
	StartTime string
	Title     string
	Category  ItineraryCategory
	Notes     string
	CostCents *int64
	Currency  *string
	Position  int32
}

func (q *Queries) ItemByID(ctx context.Context, arg ItemByIDParams) (ItemByIDRow, error) {
	row := q.db.QueryRow(ctx, itemByID, arg.TripID, arg.ID)
	var i ItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StopID,
		&i.Day,
		&i.StartTime,
		&i.Title,
		&i.Category,
		&i.Notes,
		&i.CostCents,
		&i.Currency,
		&i.Position,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, trip_id, stop_id, day, CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time, title, category, notes, cost_cents, currency, position
FROM itinerary_items WHERE trip_id = $1 ORDER BY day, position
`

type ListItemsRow struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	StopID    *uuid.UUID
	Day       time.Time
	StartTime string
	Title     string
	Category  ItineraryCategory
	Notes     string
	CostCents *int64
	Currency  *string
	Position  int32
}

func (q *Queries) ListItems(ctx context.Context, tripID uuid.UUID) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.StopID,
			&i.Day,
			&i.StartTime,
			&i.Title,
			&i.Category,
			&i.Notes,
			&i.CostCents,
			&i.Currency,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offsetItemPositions = `-- name: OffsetItemPositions :exec
UPDATE itinerary_items SET position = position + $3 WHERE trip_id = $1 AND day = $2
`

type OffsetItemPositionsParams struct {
	TripID   uuid.UUID
	Day      time.Time
	Position int32
}

func (q *Queries) OffsetItemPositions(ctx context.Context, arg OffsetItemPositionsParams) error {
	_, err := q.db.Exec(ctx, offsetItemPositions, arg.TripID, arg.Day, arg.Position)
	return err
}

const setItemPosition = `-- name: SetItemPosition :execrows
UPDATE itinerary_items SET position = $4 WHERE id = $3 AND trip_id = $1 AND day = $2
`

type SetItemPositionParams struct {
	TripID   uuid.UUID
	Day      time.Time
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetItemPosition(ctx context.Context, arg SetItemPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemPosition,
		arg.TripID,
		arg.Day,
		arg.ID,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE itinerary_items
SET stop_id = $1, day = $2, start_time = NULLIF($3::text, '')::time,
    title = $4, category = $5, notes = $6,
    cost_cents = $7, currency = $8
WHERE id = $9 AND trip_id = $10
RETURNING id, trip_id, stop_id, day, CAST(COALESCE(to_char(start_time, 'HH24:MI'), '') AS text) AS start_time, title, category, notes, cost_cents, currency, position
`

type UpdateItemParams struct {
	StopID    *uuid.UUID
	Day       time.Time
	StartTime string
	Title     string
	Category  ItineraryCategory
	Notes     string
	CostCents *int64
	Currency  *string
	ID        uuid.UUID
	TripID    uuid.UUID
}

type UpdateItemRow struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	StopID    *uuid.UUID
	Day       time.Time
	StartTime string
	Title     string
	Category  ItineraryCategory
	Notes     string
	CostCents *int64
	Currency  *string
	Position  int32
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.StopID,
		arg.Day,
		arg.StartTime,
		arg.Title,
		arg.Category,
		arg.Notes,
		arg.CostCents,
		arg.Currency,
		arg.ID,
		arg.TripID,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StopID,
		&i.Day,
		&i.StartTime,
		&i.Title,
		&i.Category,
		&i.Notes,
		&i.CostCents,
		&i.Currency,
		&i.Position,
	)
	return i, err
}
