// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (trip_id, author_id, entry_date, title, body, lat, lon)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, trip_id, author_id, entry_date, title, body, lat, lon, created_at, updated_at
`

type CreateJournalEntryParams struct {
	TripID    uuid.UUID
	AuthorID  uuid.UUID
	EntryDate time.Time
	Title     string
	Body      string
	Lat       *float64
	Lon       *float64
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.TripID,
		arg.AuthorID,
		arg.EntryDate,
		arg.Title,
		arg.Body,
		arg.Lat,
		arg.Lon,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.AuthorID,
		&i.EntryDate,
		&i.Title,
		&i.Body,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJournalPhoto = `-- name: CreateJournalPhoto :one
INSERT INTO journal_photos (id, entry_id, file_path, content_type, size_bytes, taken_at, lat, lon, caption)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, entry_id, file_path, content_type, size_bytes, taken_at, lat, lon, caption, created_at
`

type CreateJournalPhotoParams struct {
	ID          uuid.UUID
	EntryID     uuid.UUID
	FilePath    string
	ContentType string
	SizeBytes   int64
	TakenAt     *time.Time
	Lat         *float64
	Lon         *float64
	Caption     string
}

// The ID is supplied by the caller because the file on disk is named after it.
func (q *Queries) CreateJournalPhoto(ctx context.Context, arg CreateJournalPhotoParams) (JournalPhoto, error) {
	row := q.db.QueryRow(ctx, createJournalPhoto,
		arg.ID,
		arg.EntryID,
		arg.FilePath,
		arg.ContentType,
		arg.SizeBytes,
		arg.TakenAt,
		arg.Lat,
		arg.Lon,
		arg.Caption,
	)
	var i JournalPhoto
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.FilePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.TakenAt,
		&i.Lat,
		&i.Lon,
		&i.Caption,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJournalEntry = `-- name: DeleteJournalEntry :execrows
DELETE FROM journal_entries WHERE id = $2 AND trip_id = $1
`

type DeleteJournalEntryParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteJournalEntry(ctx context.Context, arg DeleteJournalEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJournalEntry, arg.TripID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJournalPhoto = `-- name: DeleteJournalPhoto :one
DELETE FROM journal_photos p
USING journal_entries e
WHERE p.id = $2 AND p.entry_id = e.id AND e.trip_id = $1
RETURNING p.id, p.entry_id, p.file_path, p.content_type, p.size_bytes, p.taken_at, p.lat, p.lon, p.caption, p.created_at
`

type DeleteJournalPhotoParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

// Returns the deleted row so the caller can remove the file from disk.
func (q *Queries) DeleteJournalPhoto(ctx context.Context, arg DeleteJournalPhotoParams) (JournalPhoto, error) {
	row := q.db.QueryRow(ctx, deleteJournalPhoto, arg.TripID, arg.ID)
	var i JournalPhoto
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.FilePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.TakenAt,
		&i.Lat,
		&i.Lon,
		&i.Caption,
		&i.CreatedAt,
	)
	return i, err
}

const journalEntryByID = `-- name: JournalEntryByID :one
SELECT id, trip_id, author_id, entry_date, title, body, lat, lon, created_at, updated_at FROM journal_entries WHERE id = $2 AND trip_id = $1
`

type JournalEntryByIDParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) JournalEntryByID(ctx context.Context, arg JournalEntryByIDParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, journalEntryByID, arg.TripID, arg.ID)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.AuthorID,
		&i.EntryDate,
		&i.Title,
		&i.Body,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const journalPhotoWithOwner = `-- name: JournalPhotoWithOwner :one
SELECT p.id, p.entry_id, p.file_path, p.content_type, p.size_bytes, p.taken_at, p.lat, p.lon, p.caption, p.created_at, t.owner_id FROM journal_photos p
JOIN journal_entries e ON e.id = p.entry_id
JOIN trips t ON t.id = e.trip_id
WHERE p.id = $1
`

type JournalPhotoWithOwnerRow struct {
	ID          uuid.UUID
	EntryID     uuid.UUID
	FilePath    string
	ContentType string
	SizeBytes   int64
	TakenAt     *time.Time
	Lat         *float64
	Lon         *float64
	Caption     string
	CreatedAt   time.Time
	OwnerID     uuid.UUID
}

// Resolves a photo to its file plus the owning user, for authorized serving.
func (q *Queries) JournalPhotoWithOwner(ctx context.Context, id uuid.UUID) (JournalPhotoWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, journalPhotoWithOwner, id)
	var i JournalPhotoWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.FilePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.TakenAt,
		&i.Lat,
		&i.Lon,
		&i.Caption,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, trip_id, author_id, entry_date, title, body, lat, lon, created_at, updated_at FROM journal_entries
WHERE trip_id = $1
ORDER BY entry_date, created_at
`

func (q *Queries) ListJournalEntries(ctx context.Context, tripID uuid.UUID) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntries, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.AuthorID,
			&i.EntryDate,
			&i.Title,
			&i.Body,
			&i.Lat,
			&i.Lon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalPhotosForEntry = `-- name: ListJournalPhotosForEntry :many
SELECT id, entry_id, file_path, content_type, size_bytes, taken_at, lat, lon, caption, created_at FROM journal_photos WHERE entry_id = $1 ORDER BY taken_at NULLS LAST, created_at
`

func (q *Queries) ListJournalPhotosForEntry(ctx context.Context, entryID uuid.UUID) ([]JournalPhoto, error) {
	rows, err := q.db.Query(ctx, listJournalPhotosForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalPhoto
	for rows.Next() {
		var i JournalPhoto
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.FilePath,
			&i.ContentType,
			&i.SizeBytes,
			&i.TakenAt,
			&i.Lat,
			&i.Lon,
			&i.Caption,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalPhotosForTrip = `-- name: ListJournalPhotosForTrip :many
SELECT p.id, p.entry_id, p.file_path, p.content_type, p.size_bytes, p.taken_at, p.lat, p.lon, p.caption, p.created_at FROM journal_photos p
JOIN journal_entries e ON e.id = p.entry_id
WHERE e.trip_id = $1
ORDER BY p.taken_at NULLS LAST, p.created_at
`

// Photos for all of a trip's entries, for embedding into the journal listing.
func (q *Queries) ListJournalPhotosForTrip(ctx context.Context, tripID uuid.UUID) ([]JournalPhoto, error) {
	rows, err := q.db.Query(ctx, listJournalPhotosForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalPhoto
	for rows.Next() {
		var i JournalPhoto
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.FilePath,
			&i.ContentType,
			&i.SizeBytes,
			&i.TakenAt,
			&i.Lat,
			&i.Lon,
			&i.Caption,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalEntry = `-- name: UpdateJournalEntry :one
UPDATE journal_entries
SET entry_date = $3, title = $4, body = $5, lat = $6, lon = $7, updated_at = now()
WHERE id = $2 AND trip_id = $1
RETURNING id, trip_id, author_id, entry_date, title, body, lat, lon, created_at, updated_at
`

type UpdateJournalEntryParams struct {
	TripID    uuid.UUID
	ID        uuid.UUID
	EntryDate time.Time
	Title     string
	Body      string
	Lat       *float64
	Lon       *float64
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, updateJournalEntry,
		arg.TripID,
		arg.ID,
		arg.EntryDate,
		arg.Title,
		arg.Body,
		arg.Lat,
		arg.Lon,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.AuthorID,
		&i.EntryDate,
		&i.Title,
		&i.Body,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
