// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: layers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const ensureFinalLayer = `-- name: EnsureFinalLayer :one
INSERT INTO itinerary_layers (trip_id, owner_id, name)
VALUES ($1, NULL, 'Final')
ON CONFLICT (trip_id) WHERE owner_id IS NULL
DO UPDATE SET name = itinerary_layers.name
RETURNING id, trip_id, owner_id, name, color, created_at
`

// Creates the trip's Final layer on first use (new trips get one lazily).
func (q *Queries) EnsureFinalLayer(ctx context.Context, tripID uuid.UUID) (ItineraryLayer, error) {
	row := q.db.QueryRow(ctx, ensureFinalLayer, tripID)
	var i ItineraryLayer
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const layerByID = `-- name: LayerByID :one
SELECT id, trip_id, owner_id, name, color, created_at FROM itinerary_layers WHERE id = $2 AND trip_id = $1
`

type LayerByIDParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) LayerByID(ctx context.Context, arg LayerByIDParams) (ItineraryLayer, error) {
	row := q.db.QueryRow(ctx, layerByID, arg.TripID, arg.ID)
	var i ItineraryLayer
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLayers = `-- name: ListLayers :many
SELECT id, trip_id, owner_id, name, color, created_at FROM itinerary_layers WHERE trip_id = $1 ORDER BY (owner_id IS NOT NULL), created_at
`

func (q *Queries) ListLayers(ctx context.Context, tripID uuid.UUID) ([]ItineraryLayer, error) {
	rows, err := q.db.Query(ctx, listLayers, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryLayer
	for rows.Next() {
		var i ItineraryLayer
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
