// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: layers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createLayer = `-- name: CreateLayer :one
INSERT INTO itinerary_layers (trip_id, owner_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, trip_id, owner_id, name, color, created_at
`

type CreateLayerParams struct {
	TripID  uuid.UUID
	OwnerID *uuid.UUID
	Name    string
	Color   string
}

// A member's named layer; anyone on the trip can hold several.
func (q *Queries) CreateLayer(ctx context.Context, arg CreateLayerParams) (ItineraryLayer, error) {
	row := q.db.QueryRow(ctx, createLayer,
		arg.TripID,
		arg.OwnerID,
		arg.Name,
		arg.Color,
	)
	var i ItineraryLayer
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProposalLayer = `-- name: DeleteProposalLayer :execrows
DELETE FROM itinerary_layers WHERE id = $2 AND trip_id = $1 AND owner_id IS NOT NULL
`

type DeleteProposalLayerParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

// The Plan layer (owner_id NULL) is never deletable; items cascade.
func (q *Queries) DeleteProposalLayer(ctx context.Context, arg DeleteProposalLayerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProposalLayer, arg.TripID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensurePlanLayer = `-- name: EnsurePlanLayer :one
INSERT INTO itinerary_layers (trip_id, owner_id, name)
VALUES ($1, NULL, 'Plan')
ON CONFLICT (trip_id) WHERE owner_id IS NULL
DO UPDATE SET name = itinerary_layers.name
RETURNING id, trip_id, owner_id, name, color, created_at
`

// The trip's shared Plan layer (owner_id NULL), created on first use.
func (q *Queries) EnsurePlanLayer(ctx context.Context, tripID uuid.UUID) (ItineraryLayer, error) {
	row := q.db.QueryRow(ctx, ensurePlanLayer, tripID)
	var i ItineraryLayer
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const layerByID = `-- name: LayerByID :one
SELECT id, trip_id, owner_id, name, color, created_at FROM itinerary_layers WHERE id = $2 AND trip_id = $1
`

type LayerByIDParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) LayerByID(ctx context.Context, arg LayerByIDParams) (ItineraryLayer, error) {
	row := q.db.QueryRow(ctx, layerByID, arg.TripID, arg.ID)
	var i ItineraryLayer
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLayers = `-- name: ListLayers :many
SELECT id, trip_id, owner_id, name, color, created_at FROM itinerary_layers WHERE trip_id = $1 ORDER BY (owner_id IS NOT NULL), created_at
`

func (q *Queries) ListLayers(ctx context.Context, tripID uuid.UUID) ([]ItineraryLayer, error) {
	rows, err := q.db.Query(ctx, listLayers, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryLayer
	for rows.Next() {
		var i ItineraryLayer
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLayer = `-- name: UpdateLayer :one
UPDATE itinerary_layers SET name = $3, color = $4
WHERE id = $2 AND trip_id = $1
RETURNING id, trip_id, owner_id, name, color, created_at
`

type UpdateLayerParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
	Name   string
	Color  string
}

func (q *Queries) UpdateLayer(ctx context.Context, arg UpdateLayerParams) (ItineraryLayer, error) {
	row := q.db.QueryRow(ctx, updateLayer,
		arg.TripID,
		arg.ID,
		arg.Name,
		arg.Color,
	)
	var i ItineraryLayer
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
