// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listAccessibleTrips = `-- name: ListAccessibleTrips :many
SELECT t.id, t.owner_id, t.title, t.description, t.status, t.start_date, t.end_date, t.cover_photo, t.created_at, t.updated_at,
       CAST(CASE WHEN t.owner_id = $1 THEN 'owner' ELSE m.role::text END AS text) AS role
FROM trips t
LEFT JOIN trip_members m ON m.trip_id = t.id AND m.user_id = $1
WHERE t.owner_id = $1 OR m.user_id IS NOT NULL
ORDER BY COALESCE(t.start_date, t.created_at::date) DESC, t.created_at DESC
`

type ListAccessibleTripsRow struct {
	Trip Trip
	Role string
}

// Trips the user owns or is a member of, with their role annotated.
func (q *Queries) ListAccessibleTrips(ctx context.Context, ownerID uuid.UUID) ([]ListAccessibleTripsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleTrips, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleTripsRow
	for rows.Next() {
		var i ListAccessibleTripsRow
		if err := rows.Scan(
			&i.Trip.ID,
			&i.Trip.OwnerID,
			&i.Trip.Title,
			&i.Trip.Description,
			&i.Trip.Status,
			&i.Trip.StartDate,
			&i.Trip.EndDate,
			&i.Trip.CoverPhoto,
			&i.Trip.CreatedAt,
			&i.Trip.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, m.role, m.created_at, u.email, u.display_name, u.avatar_url
FROM trip_members m
JOIN users u ON u.id = m.user_id
WHERE m.trip_id = $1
ORDER BY m.created_at
`

type ListMembersRow struct {
	UserID      uuid.UUID
	Role        TripRole
	CreatedAt   time.Time
	Email       string
	DisplayName string
	AvatarURL   *string
}

func (q *Queries) ListMembers(ctx context.Context, tripID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.DisplayName,
			&i.AvatarURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM trip_members WHERE trip_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	TripID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.TripID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tripWithRole = `-- name: TripWithRole :one
SELECT t.id, t.owner_id, t.title, t.description, t.status, t.start_date, t.end_date, t.cover_photo, t.created_at, t.updated_at,
       CAST(CASE WHEN t.owner_id = $2 THEN 'owner' ELSE COALESCE(m.role::text, '') END AS text) AS role
FROM trips t
LEFT JOIN trip_members m ON m.trip_id = t.id AND m.user_id = $2
WHERE t.id = $1
`

type TripWithRoleParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type TripWithRoleRow struct {
	Trip Trip
	Role string
}

// Loads a trip together with the requesting user's role on it: 'owner',
// a membership role, or ” for no access.
func (q *Queries) TripWithRole(ctx context.Context, arg TripWithRoleParams) (TripWithRoleRow, error) {
	row := q.db.QueryRow(ctx, tripWithRole, arg.ID, arg.OwnerID)
	var i TripWithRoleRow
	err := row.Scan(
		&i.Trip.ID,
		&i.Trip.OwnerID,
		&i.Trip.Title,
		&i.Trip.Description,
		&i.Trip.Status,
		&i.Trip.StartDate,
		&i.Trip.EndDate,
		&i.Trip.CoverPhoto,
		&i.Trip.CreatedAt,
		&i.Trip.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const upsertMember = `-- name: UpsertMember :one
INSERT INTO trip_members (trip_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (trip_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING trip_id, user_id, role, created_at
`

type UpsertMemberParams struct {
	TripID uuid.UUID
	UserID uuid.UUID
	Role   TripRole
}

// Adding an existing member updates their role instead of failing.
func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, upsertMember, arg.TripID, arg.UserID, arg.Role)
	var i TripMember
	err := row.Scan(
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
