// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ItineraryCategory string

const (
	ItineraryCategoryActivity  ItineraryCategory = "activity"
	ItineraryCategoryFood      ItineraryCategory = "food"
	ItineraryCategoryLodging   ItineraryCategory = "lodging"
	ItineraryCategoryTransport ItineraryCategory = "transport"
	ItineraryCategoryOther     ItineraryCategory = "other"
	ItineraryCategoryFlight    ItineraryCategory = "flight"
	ItineraryCategoryTrain     ItineraryCategory = "train"
)

func (e *ItineraryCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItineraryCategory(s)
	case string:
		*e = ItineraryCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ItineraryCategory: %T", src)
	}
	return nil
}

type NullItineraryCategory struct {
	ItineraryCategory ItineraryCategory
	Valid             bool // Valid is true if ItineraryCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItineraryCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ItineraryCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItineraryCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItineraryCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItineraryCategory), nil
}

type TripRole string

const (
	TripRoleViewer TripRole = "viewer"
	TripRoleEditor TripRole = "editor"
)

func (e *TripRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripRole(s)
	case string:
		*e = TripRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TripRole: %T", src)
	}
	return nil
}

type NullTripRole struct {
	TripRole TripRole
	Valid    bool // Valid is true if TripRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripRole) Scan(value interface{}) error {
	if value == nil {
		ns.TripRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripRole), nil
}

type TripStatus string

const (
	TripStatusPlanning  TripStatus = "planning"
	TripStatusActive    TripStatus = "active"
	TripStatusCompleted TripStatus = "completed"
)

func (e *TripStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripStatus(s)
	case string:
		*e = TripStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripStatus: %T", src)
	}
	return nil
}

type NullTripStatus struct {
	TripStatus TripStatus
	Valid      bool // Valid is true if TripStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripStatus), nil
}

type Home struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Lat       float64
	Lon       float64
	CreatedAt time.Time
}

type ItineraryItem struct {
	ID                uuid.UUID
	TripID            uuid.UUID
	StopID            *uuid.UUID
	Day               time.Time
	StartTime         string
	Title             string
	Category          ItineraryCategory
	Notes             string
	CostCents         *int64
	Currency          *string
	Position          int32
	EndTime           string
	DestinationStopID *uuid.UUID
	OriginHomeID      *uuid.UUID
	DestinationHomeID *uuid.UUID
	Address           string
	Lat               *float64
	Lon               *float64
	LayerID           uuid.UUID
}

type ItineraryLayer struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	OwnerID   *uuid.UUID
	Name      string
	Color     string
	CreatedAt time.Time
}

type JournalEntry struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	AuthorID  uuid.UUID
	EntryDate time.Time
	Title     string
	Body      string
	Lat       *float64
	Lon       *float64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type JournalPhoto struct {
	ID          uuid.UUID
	EntryID     uuid.UUID
	FilePath    string
	ContentType string
	SizeBytes   int64
	TakenAt     *time.Time
	Lat         *float64
	Lon         *float64
	Caption     string
	CreatedAt   time.Time
}

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
}

type ShareLink struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	Token     string
	CreatedAt time.Time
}

type Stop struct {
	ID            uuid.UUID
	TripID        uuid.UUID
	Name          string
	Lat           *float64
	Lon           *float64
	ArrivalDate   *time.Time
	DepartureDate *time.Time
	Position      int32
	Notes         string
}

type Trip struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description string
	Status      TripStatus
	StartDate   *time.Time
	EndDate     *time.Time
	CoverPhoto  *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TripMember struct {
	TripID    uuid.UUID
	UserID    uuid.UUID
	Role      TripRole
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	AvatarURL    *string
	GoogleSub    *string
	PasswordHash *string
	IsAdmin      bool
	CreatedAt    time.Time
}
