// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const sessionUserByToken = `-- name: SessionUserByToken :one
UPDATE sessions SET last_seen_at = now()
FROM users
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
  AND users.id = sessions.user_id
RETURNING users.id, users.email, users.display_name, users.avatar_url, users.google_sub, users.password_hash, users.is_admin, users.created_at, users.calendar_token, users.mcp_token, users.oidc_sub
`

// Resolves an unexpired session to its user and bumps last_seen_at.
func (q *Queries) SessionUserByToken(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, sessionUserByToken, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
		&i.OidcSub,
	)
	return i, err
}
