// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (trip_id, token)
VALUES ($1, $2)
RETURNING id, trip_id, token, created_at
`

type CreateShareLinkParams struct {
	TripID uuid.UUID
	Token  string
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink, arg.TripID, arg.Token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShareLink = `-- name: DeleteShareLink :execrows
DELETE FROM share_links WHERE trip_id = $1 AND id = $2
`

type DeleteShareLinkParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteShareLink(ctx context.Context, arg DeleteShareLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShareLink, arg.TripID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listShareLinks = `-- name: ListShareLinks :many
SELECT id, trip_id, token, created_at FROM share_links WHERE trip_id = $1 ORDER BY created_at
`

func (q *Queries) ListShareLinks(ctx context.Context, tripID uuid.UUID) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, listShareLinks, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareLink
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Token,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tripByShareToken = `-- name: TripByShareToken :one
SELECT t.id, t.owner_id, t.title, t.description, t.status, t.start_date, t.end_date, t.cover_photo, t.created_at, t.updated_at FROM trips t
JOIN share_links s ON s.trip_id = t.id
WHERE s.token = $1
`

func (q *Queries) TripByShareToken(ctx context.Context, token string) (Trip, error) {
	row := q.db.QueryRow(ctx, tripByShareToken, token)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhoto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
