// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listLocatedStopsForUser = `-- name: ListLocatedStopsForUser :many
SELECT s.id, s.name, s.lat, s.lon, s.position, t.id AS trip_id, t.title AS trip_title, t.start_date, t.end_date
FROM stops s
JOIN trips t ON t.id = s.trip_id
LEFT JOIN trip_members m ON m.trip_id = t.id AND m.user_id = $1
WHERE (t.owner_id = $1 OR m.user_id IS NOT NULL)
  AND s.lat IS NOT NULL
ORDER BY t.id, s.position
`

type ListLocatedStopsForUserRow struct {
	ID        uuid.UUID
	Name      string
	Lat       *float64
	Lon       *float64
	Position  int32
	TripID    uuid.UUID
	TripTitle string
	StartDate *time.Time
	EndDate   *time.Time
}

// Every located stop across trips the user can see, in route order —
// the raw material for the stats page and visited-places map.
func (q *Queries) ListLocatedStopsForUser(ctx context.Context, userID uuid.UUID) ([]ListLocatedStopsForUserRow, error) {
	rows, err := q.db.Query(ctx, listLocatedStopsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocatedStopsForUserRow
	for rows.Next() {
		var i ListLocatedStopsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.Position,
			&i.TripID,
			&i.TripTitle,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTravelLegsForUser = `-- name: ListTravelLegsForUser :many
SELECT i.category, i.trip_id, i.stop_id, i.destination_stop_id,
       CAST(COALESCE(to_char(i.start_time, 'HH24:MI'), '') AS text) AS start_time,
       CAST(COALESCE(to_char(i.end_time, 'HH24:MI'), '') AS text) AS end_time,
       s1.lat AS from_stop_lat, s1.lon AS from_stop_lon,
       s2.lat AS to_stop_lat, s2.lon AS to_stop_lon,
       h1.lat AS from_home_lat, h1.lon AS from_home_lon,
       h2.lat AS to_home_lat, h2.lon AS to_home_lon
FROM itinerary_items i
JOIN itinerary_layers l ON l.id = i.layer_id AND l.visible
JOIN trips t ON t.id = i.trip_id
LEFT JOIN trip_members m ON m.trip_id = t.id AND m.user_id = $1
LEFT JOIN stops s1 ON s1.id = i.stop_id
LEFT JOIN stops s2 ON s2.id = i.destination_stop_id
LEFT JOIN homes h1 ON h1.id = i.origin_home_id
LEFT JOIN homes h2 ON h2.id = i.destination_home_id
WHERE i.category IN ('flight', 'train') AND (t.owner_id = $1 OR m.user_id IS NOT NULL)
`

type ListTravelLegsForUserRow struct {
	Category          ItineraryCategory
	TripID            uuid.UUID
	StopID            *uuid.UUID
	DestinationStopID *uuid.UUID
	StartTime         string
	EndTime           string
	FromStopLat       *float64
	FromStopLon       *float64
	ToStopLat         *float64
	ToStopLon         *float64
	FromHomeLat       *float64
	FromHomeLon       *float64
	ToHomeLat         *float64
	ToHomeLon         *float64
}

// Flight and train items across accessible trips. Each endpoint is either a
// stop or a home; the joins surface whichever coordinates exist.
func (q *Queries) ListTravelLegsForUser(ctx context.Context, userID uuid.UUID) ([]ListTravelLegsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTravelLegsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTravelLegsForUserRow
	for rows.Next() {
		var i ListTravelLegsForUserRow
		if err := rows.Scan(
			&i.Category,
			&i.TripID,
			&i.StopID,
			&i.DestinationStopID,
			&i.StartTime,
			&i.EndTime,
			&i.FromStopLat,
			&i.FromStopLon,
			&i.ToStopLat,
			&i.ToStopLon,
			&i.FromHomeLat,
			&i.FromHomeLon,
			&i.ToHomeLat,
			&i.ToHomeLon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
