// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listLocatedStopsForUser = `-- name: ListLocatedStopsForUser :many
SELECT s.name, s.lat, s.lon, s.position, t.id AS trip_id, t.title AS trip_title
FROM stops s
JOIN trips t ON t.id = s.trip_id
LEFT JOIN trip_members m ON m.trip_id = t.id AND m.user_id = $1
WHERE (t.owner_id = $1 OR m.user_id IS NOT NULL)
  AND s.lat IS NOT NULL
ORDER BY t.id, s.position
`

type ListLocatedStopsForUserRow struct {
	Name      string
	Lat       *float64
	Lon       *float64
	Position  int32
	TripID    uuid.UUID
	TripTitle string
}

// Every located stop across trips the user can see, in route order —
// the raw material for the stats page and visited-places map.
func (q *Queries) ListLocatedStopsForUser(ctx context.Context, userID uuid.UUID) ([]ListLocatedStopsForUserRow, error) {
	rows, err := q.db.Query(ctx, listLocatedStopsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocatedStopsForUserRow
	for rows.Next() {
		var i ListLocatedStopsForUserRow
		if err := rows.Scan(
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.Position,
			&i.TripID,
			&i.TripTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
