// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stops.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStops = `-- name: CountStops :one
SELECT count(*) FROM stops WHERE trip_id = $1
`

func (q *Queries) CountStops(ctx context.Context, tripID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStops, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStop = `-- name: CreateStop :one
INSERT INTO stops (trip_id, name, lat, lon, arrival_date, departure_date, notes, position)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        (SELECT COALESCE(MAX(position) + 1, 0) FROM stops WHERE trip_id = $1))
RETURNING id, trip_id, name, lat, lon, arrival_date, departure_date, position, notes
`

type CreateStopParams struct {
	TripID        uuid.UUID
	Name          string
	Lat           *float64
	Lon           *float64
	ArrivalDate   *time.Time
	DepartureDate *time.Time
	Notes         string
}

// Appends the stop at the end of the trip's ordering.
func (q *Queries) CreateStop(ctx context.Context, arg CreateStopParams) (Stop, error) {
	row := q.db.QueryRow(ctx, createStop,
		arg.TripID,
		arg.Name,
		arg.Lat,
		arg.Lon,
		arg.ArrivalDate,
		arg.DepartureDate,
		arg.Notes,
	)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.Position,
		&i.Notes,
	)
	return i, err
}

const deleteStop = `-- name: DeleteStop :execrows
DELETE FROM stops WHERE id = $2 AND trip_id = $1
`

type DeleteStopParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteStop(ctx context.Context, arg DeleteStopParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStop, arg.TripID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStops = `-- name: ListStops :many
SELECT id, trip_id, name, lat, lon, arrival_date, departure_date, position, notes FROM stops WHERE trip_id = $1 ORDER BY position
`

func (q *Queries) ListStops(ctx context.Context, tripID uuid.UUID) ([]Stop, error) {
	rows, err := q.db.Query(ctx, listStops, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stop
	for rows.Next() {
		var i Stop
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.Position,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offsetStopPositions = `-- name: OffsetStopPositions :exec
UPDATE stops SET position = position + $2 WHERE trip_id = $1
`

type OffsetStopPositionsParams struct {
	TripID   uuid.UUID
	Position int32
}

// Shifts all positions up so a reorder never collides with target positions.
func (q *Queries) OffsetStopPositions(ctx context.Context, arg OffsetStopPositionsParams) error {
	_, err := q.db.Exec(ctx, offsetStopPositions, arg.TripID, arg.Position)
	return err
}

const setStopPosition = `-- name: SetStopPosition :execrows
UPDATE stops SET position = $3 WHERE id = $2 AND trip_id = $1
`

type SetStopPositionParams struct {
	TripID   uuid.UUID
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetStopPosition(ctx context.Context, arg SetStopPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStopPosition, arg.TripID, arg.ID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopByID = `-- name: StopByID :one
SELECT id, trip_id, name, lat, lon, arrival_date, departure_date, position, notes FROM stops WHERE id = $2 AND trip_id = $1
`

type StopByIDParams struct {
	TripID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) StopByID(ctx context.Context, arg StopByIDParams) (Stop, error) {
	row := q.db.QueryRow(ctx, stopByID, arg.TripID, arg.ID)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.Position,
		&i.Notes,
	)
	return i, err
}

const updateStop = `-- name: UpdateStop :one
UPDATE stops
SET name = $3, lat = $4, lon = $5, arrival_date = $6, departure_date = $7, notes = $8
WHERE id = $2 AND trip_id = $1
RETURNING id, trip_id, name, lat, lon, arrival_date, departure_date, position, notes
`

type UpdateStopParams struct {
	TripID        uuid.UUID
	ID            uuid.UUID
	Name          string
	Lat           *float64
	Lon           *float64
	ArrivalDate   *time.Time
	DepartureDate *time.Time
	Notes         string
}

func (q *Queries) UpdateStop(ctx context.Context, arg UpdateStopParams) (Stop, error) {
	row := q.db.QueryRow(ctx, updateStop,
		arg.TripID,
		arg.ID,
		arg.Name,
		arg.Lat,
		arg.Lon,
		arg.ArrivalDate,
		arg.DepartureDate,
		arg.Notes,
	)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.Position,
		&i.Notes,
	)
	return i, err
}
