// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (owner_id, title, description, status, start_date, end_date, cover_photo)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, title, description, status, start_date, end_date, cover_photo, created_at, updated_at
`

type CreateTripParams struct {
	OwnerID     uuid.UUID
	Title       string
	Description string
	Status      TripStatus
	StartDate   *time.Time
	EndDate     *time.Time
	CoverPhoto  *string
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CoverPhoto,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhoto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :execrows
DELETE FROM trips WHERE id = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrip, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTripsByOwner = `-- name: ListTripsByOwner :many
SELECT id, owner_id, title, description, status, start_date, end_date, cover_photo, created_at, updated_at FROM trips
WHERE owner_id = $1
ORDER BY COALESCE(start_date, created_at::date) DESC, created_at DESC
`

func (q *Queries) ListTripsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CoverPhoto,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTrip = `-- name: TouchTrip :exec
UPDATE trips SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchTrip(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTrip, id)
	return err
}

const tripByID = `-- name: TripByID :one
SELECT id, owner_id, title, description, status, start_date, end_date, cover_photo, created_at, updated_at FROM trips WHERE id = $1
`

func (q *Queries) TripByID(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, tripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhoto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET title = $2, description = $3, status = $4, start_date = $5,
    end_date = $6, cover_photo = $7, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, title, description, status, start_date, end_date, cover_photo, created_at, updated_at
`

type UpdateTripParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	Status      TripStatus
	StartDate   *time.Time
	EndDate     *time.Time
	CoverPhoto  *string
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CoverPhoto,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CoverPhoto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
