// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, avatar_url, google_sub, password_hash, is_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token
`

type CreateUserParams struct {
	Email        string
	DisplayName  string
	AvatarURL    *string
	GoogleSub    *string
	PasswordHash *string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarURL,
		arg.GoogleSub,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const linkGoogle = `-- name: LinkGoogle :one
UPDATE users SET google_sub = $2, display_name = $3, avatar_url = $4
WHERE id = $1
RETURNING id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token
`

type LinkGoogleParams struct {
	ID          uuid.UUID
	GoogleSub   *string
	DisplayName string
	AvatarURL   *string
}

func (q *Queries) LinkGoogle(ctx context.Context, arg LinkGoogleParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogle,
		arg.ID,
		arg.GoogleSub,
		arg.DisplayName,
		arg.AvatarURL,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const setCalendarToken = `-- name: SetCalendarToken :one
UPDATE users SET calendar_token = $2 WHERE id = $1
RETURNING id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token
`

type SetCalendarTokenParams struct {
	ID            uuid.UUID
	CalendarToken *string
}

// NULL clears the token, disabling the user's calendar feed.
func (q *Queries) SetCalendarToken(ctx context.Context, arg SetCalendarTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, setCalendarToken, arg.ID, arg.CalendarToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const setMCPToken = `-- name: SetMCPToken :one
UPDATE users SET mcp_token = $2 WHERE id = $1
RETURNING id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token
`

type SetMCPTokenParams struct {
	ID       uuid.UUID
	McpToken *string
}

// NULL clears the token, disabling the user's MCP access.
func (q *Queries) SetMCPToken(ctx context.Context, arg SetMCPTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, setMCPToken, arg.ID, arg.McpToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const setPassword = `-- name: SetPassword :one
UPDATE users SET password_hash = $2 WHERE id = $1
RETURNING id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token
`

type SetPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2, avatar_url = $3 WHERE id = $1
RETURNING id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID
	DisplayName string
	AvatarURL   *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.AvatarURL)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const userByCalendarToken = `-- name: UserByCalendarToken :one
SELECT id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token FROM users WHERE calendar_token = $1
`

func (q *Queries) UserByCalendarToken(ctx context.Context, calendarToken *string) (User, error) {
	row := q.db.QueryRow(ctx, userByCalendarToken, calendarToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token FROM users WHERE email = $1
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const userByGoogleSub = `-- name: UserByGoogleSub :one
SELECT id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token FROM users WHERE google_sub = $1
`

func (q *Queries) UserByGoogleSub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, userByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}

const userByMCPToken = `-- name: UserByMCPToken :one
SELECT id, email, display_name, avatar_url, google_sub, password_hash, is_admin, created_at, calendar_token, mcp_token FROM users WHERE mcp_token = $1
`

func (q *Queries) UserByMCPToken(ctx context.Context, mcpToken *string) (User, error) {
	row := q.db.QueryRow(ctx, userByMCPToken, mcpToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarURL,
		&i.GoogleSub,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.CalendarToken,
		&i.McpToken,
	)
	return i, err
}
